import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _gen(tmp_path: Path) -> tuple[str, str]:
    subprocess.run([sys.executable, "scripts/gen_ts_types.py", "--out", str(tmp_path)], cwd=ROOT, check=True)
    return (tmp_path / "contracts.ts").read_text(), (tmp_path / "skeleton.ts").read_text()


def test_generated_shapes(tmp_path):
    ts, sk = _gen(tmp_path)
    assert "// GENERATED by scripts/gen_ts_types.py" in ts
    assert 'export const EMOTIONS = ["happy", "excited", "relaxed", "anxious", "fearful", "aggressive", "disinterested", "unknown"] as const;' in ts
    assert "export type Emotion = (typeof EMOTIONS)[number];" in ts
    assert "export interface FrameEvent {" in ts
    assert "  bbox: [number, number, number, number] | null;" in ts
    assert "  body_keypoints: Record<string, [number, number, number] | null>;" in ts
    assert "  face_landmarks: [number, number][] | null;" in ts
    assert "  features: Features;" in ts
    assert "  ear_position: EarPosition | null;" in ts
    assert "  label: AudioLabel;" in ts
    assert "  scores: Partial<Record<Emotion, number>>;" in ts
    assert '  source: "rules" | "llm" | "fused";' in ts
    assert "export interface LLMResult {" in ts
    assert "export const SKELETON" in sk and '["tail_base", "tail_tip"]' in sk


def test_committed_files_are_up_to_date(tmp_path):
    ts, sk = _gen(tmp_path)
    assert (ROOT / "frontend/lib/contracts.ts").read_text() == ts, "run: python scripts/gen_ts_types.py"
    assert (ROOT / "frontend/lib/skeleton.ts").read_text() == sk, "run: python scripts/gen_ts_types.py"
