"""The Android app's contracts are generated from backend/contracts.py, and so are the JSON
fixtures its unit tests read, so neither the Kotlin types nor the fixtures can go stale.

    python scripts/gen_kotlin_types.py    # writes Contracts.kt and the test fixtures
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KOTLIN = ROOT / "android/app/src/main/java/com/btb/ondevice/contracts/Contracts.kt"
FIXTURES = ROOT / "android/app/src/test/resources/contracts"
SCRIPT = "scripts/gen_kotlin_types.py"


def _gen(tmp_path: Path) -> tuple[str, dict[str, str]]:
    out, fx = tmp_path / "kotlin", tmp_path / "fixtures"
    subprocess.run(
        [sys.executable, SCRIPT, "--out", str(out), "--fixtures", str(fx)], cwd=ROOT, check=True
    )
    return (out / "Contracts.kt").read_text(), {p.name: p.read_text() for p in sorted(fx.glob("*.json"))}


def test_generated_kotlin_shape(tmp_path):
    kt, _ = _gen(tmp_path)
    assert kt.startswith("// GENERATED by scripts/gen_kotlin_types.py from backend/contracts.py.")
    assert "package com.btb.ondevice.contracts" in kt
    # extra="forbid" on the Python side: an unknown key has to be a decode failure.
    assert "ignoreUnknownKeys = false" in kt
    # _Contract.to_json() keeps nulls, so the shape on the wire is always complete.
    assert "explicitNulls = true" in kt
    assert "encodeDefaults = true" in kt
    assert "@Serializable\ndata class Features(" in kt
    assert '    @SerialName("tail_height")\n    val tailHeight: Double? = null,' in kt
    assert "    val inFeedingZone: Boolean? = null," in kt
    assert "    val earPosition: EarPosition? = null," in kt
    assert "@Serializable\ndata class FrameEvent(" in kt
    assert "    val ts: Double," in kt
    assert "    val dogDetected: Boolean," in kt
    assert "    val bbox: List<Double>? = null," in kt
    assert '    @SerialName("bbox_conf")\n    val bboxConf: Double? = null,' in kt
    assert "    val bodyKeypoints: Map<String, List<Double>?> = emptyMap()," in kt
    assert "    val faceLandmarks: List<List<Double>>? = null," in kt
    assert "    val features: Features = Features()," in kt
    assert "    val label: AudioLabel," in kt
    assert "    val scores: Map<Emotion, Double>," in kt
    assert "    val source: EmotionStateSource," in kt
    assert '    @SerialName("latency_ms")\n    val latencyMs: Double,' in kt
    # Emotion is the fixed vocabulary, serialised by its lower-case name, in vocabulary order.
    assert "enum class Emotion {" in kt
    for emotion in ("happy", "excited", "relaxed", "anxious", "fearful", "aggressive",
                    "disinterested", "unknown"):
        assert f"    {emotion}," in kt
    assert "enum class EarPosition {" in kt and "enum class AudioLabel {" in kt
    assert "enum class EmotionStateSource {" in kt
    assert "val EMOTIONS: List<Emotion> = listOf(\n    Emotion.happy," in kt


def test_committed_kotlin_file_is_up_to_date(tmp_path):
    kt, _ = _gen(tmp_path)
    assert KOTLIN.read_text() == kt, f"run: python {SCRIPT}"


def test_committed_fixtures_are_up_to_date(tmp_path):
    _, fx = _gen(tmp_path)
    committed = {p.name: p.read_text() for p in sorted(FIXTURES.glob("*.json"))}
    assert committed == fx, f"run: python {SCRIPT}"


def test_a_fixture_exists_for_every_contract_model(tmp_path):
    _, fx = _gen(tmp_path)
    assert sorted(fx) == ["audio_event.json", "emotion_state.json", "features.json",
                          "frame_event.json", "llm_result.json", "rules_label.json"]


def test_fixtures_keep_nulls_and_the_full_score_map(tmp_path):
    """The fixtures are what prove nulls survive and RulesLabel.scores has all eight emotions."""
    _, fx = _gen(tmp_path)
    frame = json.loads(fx["frame_event.json"])
    assert frame["bbox_conf"] is None
    assert frame["face_landmarks"] is None
    assert frame["body_keypoints"]["tail_tip"] is None, "a keypoint below threshold is None, never guessed"
    assert frame["features"]["tail_height"] is None
    assert frame["features"]["ear_position"] == "up"
    assert json.loads(fx["emotion_state.json"])["snapshot"] is None
    scores = json.loads(fx["rules_label.json"])["scores"]
    assert list(scores) == ["happy", "excited", "relaxed", "anxious", "fearful", "aggressive",
                            "disinterested", "unknown"]
    assert all(0.0 <= v <= 1.0 for v in scores.values())


def test_generation_is_deterministic(tmp_path):
    first_out, first_fx = tmp_path / "a/kotlin", tmp_path / "a/fixtures"
    second_out, second_fx = tmp_path / "b/kotlin", tmp_path / "b/fixtures"
    for out, fx in ((first_out, first_fx), (second_out, second_fx)):
        subprocess.run(
            [sys.executable, SCRIPT, "--out", str(out), "--fixtures", str(fx)], cwd=ROOT, check=True
        )
    assert (first_out / "Contracts.kt").read_bytes() == (second_out / "Contracts.kt").read_bytes()
    assert {p.name: p.read_bytes() for p in first_fx.glob("*.json")} == {
        p.name: p.read_bytes() for p in second_fx.glob("*.json")
    }


def test_both_emitters_cover_the_same_models_and_vocabulary():
    """The two generators are separate scripts, so pin them to the same contract surface."""
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_kotlin_types as kotlin
    import gen_ts_types as ts

    assert [m.__name__ for m in kotlin.models()] == [m.__name__ for m in ts.MODELS]
    assert kotlin.ALIASES == {name: tuple(vals) for name, (_, vals) in ts.ALIASES.items()}