"""Generate frontend/lib/contracts.ts and frontend/lib/skeleton.ts from the pydantic contracts.

    python scripts/gen_ts_types.py            # writes into frontend/lib/
    python scripts/gen_ts_types.py --out DIR  # writes into DIR (used by tests)

tests/web/test_ts_types.py fails if the committed files are stale, so run this after changing contracts.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend import contracts as c  # noqa: E402
from backend.vision import keypoint_map as km  # noqa: E402  (pure constants; build-time only)

HEADER = "// GENERATED by scripts/gen_ts_types.py from backend/contracts.py. Do not edit.\n"
MODELS = [c.Features, c.FrameEvent, c.AudioEvent, c.RulesLabel, c.EmotionState, c.LLMResult]
ALIASES = {
    "Emotion": ("EMOTIONS", list(c.EMOTIONS)),
    "AudioLabel": ("AUDIO_LABELS", list(c.AudioLabel.__args__)),  # type: ignore[attr-defined]
    "EarPosition": ("EAR_POSITIONS", list(c.EarPosition.__args__)),  # type: ignore[attr-defined]
}


def _lit(values: list) -> str:
    for alias, (_, vals) in ALIASES.items():
        if sorted(map(str, values)) == sorted(vals):
            return alias
    return " | ".join(json.dumps(v) for v in values)


def ts_type(s: dict) -> str:
    if "$ref" in s:
        return s["$ref"].split("/")[-1]
    if "anyOf" in s:
        return " | ".join(dict.fromkeys(ts_type(x) for x in s["anyOf"]))
    if "enum" in s:
        return _lit(s["enum"])
    if "const" in s:
        return json.dumps(s["const"])
    t = s.get("type")
    if t in ("number", "integer"):
        return "number"
    if t == "string":
        return "string"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in s:
            return "[" + ", ".join(ts_type(x) for x in s["prefixItems"]) + "]"
        inner = ts_type(s.get("items", {}))
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if t == "object":
        val = ts_type(s["additionalProperties"]) if isinstance(s.get("additionalProperties"), dict) else "unknown"
        if "propertyNames" in s and "enum" in s["propertyNames"]:
            return f"Partial<Record<{_lit(s['propertyNames']['enum'])}, {val}>>"
        return f"Record<string, {val}>"
    return "unknown"


def interface(model) -> str:
    schema = model.model_json_schema(ref_template="#/$defs/{model}")
    lines = [f"export interface {model.__name__} {{"]
    for name, prop in schema["properties"].items():
        lines.append(f"  {name}: {ts_type(prop)};")
    lines.append("}")
    return "\n".join(lines)


def contracts_ts() -> str:
    parts = [HEADER]
    for alias, (const, vals) in ALIASES.items():
        parts.append(f"export const {const} = {json.dumps(vals)} as const;")
        parts.append(f"export type {alias} = (typeof {const})[number];")
    parts.append("")
    parts.extend(interface(m) + "\n" for m in MODELS)
    return "\n".join(parts).rstrip() + "\n"


def skeleton_ts() -> str:
    names = ", ".join(json.dumps(n) for n in km.CANONICAL_NAMES)
    edges = ",\n  ".join(f"[{json.dumps(a)}, {json.dumps(b)}]" for a, b in km.SKELETON)
    return (f"{HEADER}export const CANONICAL_NAMES: readonly string[] = [{names}];\n\n"
            f"export const SKELETON: readonly (readonly [string, string])[] = [\n  {edges},\n];\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "frontend" / "lib"))
    out = Path(ap.parse_args().out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "contracts.ts").write_text(contracts_ts())
    (out / "skeleton.ts").write_text(skeleton_ts())
    print(f"wrote {out / 'contracts.ts'} and {out / 'skeleton.ts'}")


if __name__ == "__main__":
    main()
