"""Generate the Android app's Kotlin mirror of the pydantic contracts, and the JSON fixtures its
unit tests read.

    python scripts/gen_kotlin_types.py                             # writes into android/
    python scripts/gen_kotlin_types.py --out DIR --fixtures DIR    # writes elsewhere (used by tests)

Writes android/app/src/main/java/com/btb/ondevice/contracts/Contracts.kt (package
com.btb.ondevice.contracts) and one android/app/src/test/resources/contracts/<model>.json per model,
each being the pydantic model's own to_json() output.

tests/web/test_kotlin_types.py fails if the committed files are stale and android ContractsTest.kt
fails if the Kotlin types stop matching those fixtures, so run this after changing contracts.py.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend import contracts as c  # noqa: E402

HEADER = (
    "// GENERATED by scripts/gen_kotlin_types.py from backend/contracts.py. Do not edit by hand.\n"
    "//\n"
    "// The pydantic models are the source of truth for the wire format; this file mirrors them field\n"
    "// for field. Regenerate with `python scripts/gen_kotlin_types.py`: tests/web/test_kotlin_types.py\n"
    "// fails while the committed file is stale, and android ContractsTest.kt fails if the types stop\n"
    "// matching the Python fixtures.\n"
)
PACKAGE = "package com.btb.ondevice.contracts\n"
KOTLIN_OUT = ROOT / "android/app/src/main/java/com/btb/ondevice/contracts"
FIXTURES_OUT = ROOT / "android/app/src/test/resources/contracts"

ALIASES = {
    "Emotion": tuple(c.EMOTIONS),
    "EarPosition": tuple(c.EarPosition.__args__),  # type: ignore[attr-defined]
    "AudioLabel": tuple(c.AudioLabel.__args__),  # type: ignore[attr-defined]
}

# One sample per model, written out by the model itself, so each fixture is pydantic's own
# to_json() output rather than a hand-written guess at it. Nulls are deliberate: _Contract.to_json()
# keeps them, so the Kotlin mirror has to keep them too.
FEATURES_SAMPLE = {
    "tail_height": None,  # keypoints missing or below the confidence threshold
    "tail_wag_hz": 2.1,
    "ear_position": "up",
    "mouth_open": None,
    "body_lowering": 0.1,
    "motion_energy": 0.7,
    "in_feeding_zone": None,
}
SAMPLES: dict[str, dict] = {
    "Features": FEATURES_SAMPLE,
    "FrameEvent": {
        "ts": 1727340000.123,
        "source": "live",
        "dog_detected": True,
        "bbox": [120.5, 240.0, 610.0, 480.25],  # x1, y1, x2, y2
        "bbox_conf": None,
        "body_keypoints": {"tail_base": [300.0, 400.0, 0.91], "tail_tip": None},
        "face_landmarks": None,
        "features": FEATURES_SAMPLE,
    },
    "AudioEvent": {"ts": 1727340000.5, "label": "bark", "score": 0.82},
    "RulesLabel": {
        "ts": 1727340001.0,
        "emotion": "excited",
        "confidence": 0.78,
        # The rules engine scores the whole vocabulary, in vocabulary order: zipped off c.EMOTIONS
        # so a new emotion breaks the generator loudly instead of quietly shipping a 7-key fixture.
        "scores": dict(
            zip(c.EMOTIONS, (0.08, 0.78, 0.05, 0.02, 0.01, 0.01, 0.03, 0.02), strict=True)
        ),
    },
    "EmotionState": {
        "ts": 1727340001.0,
        "emotion": "excited",
        "confidence": 0.78,
        "source": "fused",
        "reason": "High, fast tail wag and open mouth as the treat drops; two short yips.",
        "snapshot": None,
    },
    "LLMResult": {
        "ts": 1727340003.0,
        "emotion": "anxious",
        "confidence": 0.61,
        "reason": "Ears back and a whimper, pacing away from the bowl.",
        "provider": "groq",
        "model": "llama-3.3-70b-versatile",
        "latency_ms": 812.5,
        "trigger": "anxious for 5.0s",
    },
}

_IDENT = re.compile(r"^[a-z][a-z0-9_]*$")
_KOTLIN_KEYWORDS = {
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
    "interface", "is", "null", "object", "package", "return", "super", "this", "throw", "true",
    "try", "typealias", "typeof", "val", "var", "when", "while",
}


def models() -> list[type[c._Contract]]:  # type: ignore[name-defined]
    """Every contract model, in contracts.py's declaration order: not a hard-coded list to forget."""
    return sorted(c._Contract.__subclasses__(), key=lambda m: inspect.getsourcelines(m)[1])


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def pascal(name: str) -> str:
    return camel(name)[:1].upper() + camel(name)[1:]


def snake(name: str) -> str:
    """LLMResult -> llm_result: split on case changes, keeping acronyms together."""
    return "_".join(token.lower() for token in re.findall(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+", name))


def validated_fields(model: type[c._Contract]) -> set[str]:
    """The fields a @field_validator checks; its rule is invisible in model_json_schema()."""
    return {f for d in model.__pydantic_decorators__.field_validators.values() for f in d.info.fields}


def kdoc(text: str) -> str:
    return text.replace("*/", "*&#47;").replace("\n", " ")


# Every JSON-schema keyword this generator knows how to read. Anything else in a property schema
# raises: a constraint that silently vanishes is a contract change that only one side notices.
KNOWN_KEYWORDS = frozenset({
    "$defs", "$ref", "additionalProperties", "anyOf", "default", "description", "enum", "items",
    "maxItems", "maximum", "minItems", "minimum", "prefixItems", "properties", "propertyNames",
    "required", "title", "type",
})

# A field_validator's rule never reaches model_json_schema(), so it cannot be generated: it is
# written down here and lands on the field as KDoc. data_class refuses to emit a model whose
# validators are not all covered, so a new validator cannot slip in unnoticed.
VALIDATOR_NOTES: dict[tuple[str, str], str] = {
    ("FrameEvent", "body_keypoints"): "each value is [x, y, conf] and conf 0.0..1.0",
    ("RulesLabel", "scores"): "every score 0.0..1.0",
}


class Emitter:
    """Renders one Kotlin file. An inline Literal union becomes its own enum, named after its field."""

    def __init__(self) -> None:
        self.inline: dict[str, tuple[str, ...]] = {}

    def enum_name(self, values: tuple[str, ...], context: str) -> str:
        for alias, known in ALIASES.items():
            if values == known:
                return alias
        if not context:
            raise ValueError(f"inline Literal {list(values)} has no name to be generated from")
        return context

    def enum_body(self, values: tuple[str, ...]) -> str:
        for value in values:
            if not _IDENT.match(value) or value in _KOTLIN_KEYWORDS:
                raise ValueError(
                    f"{value!r} cannot be a Kotlin enum entry; change the contract or give the enum "
                    "an @SerialName in gen_kotlin_types.py"
                )
        return "\n".join(f"    {value}," for value in values)

    def type(self, s: dict, context: str = "") -> str:
        if "$ref" in s:
            return s["$ref"].split("/")[-1]
        if "anyOf" in s:
            members = [x for x in s["anyOf"] if x.get("type") != "null"]
            if len(members) != 1:
                raise ValueError(f"unsupported union {s['anyOf']}; Kotlin has no union type")
            return self.type(members[0], context) + ("?" if len(members) != len(s["anyOf"]) else "")
        if "enum" in s:
            values = tuple(s["enum"])
            name = self.enum_name(values, context)
            if name not in ALIASES:  # an inline union gets its own enum
                self.inline[name] = values
            return name
        t = s.get("type")
        if t in ("number", "integer"):
            return "Double"
        if t == "string":
            return "String"
        if t == "boolean":
            return "Boolean"
        if t == "array":
            inner = self.type(s["items"], context) if "items" in s else "Double"
            return f"List<{inner}>"
        if t == "object":
            value = (
                self.type(s["additionalProperties"], context)
                if isinstance(s.get("additionalProperties"), dict)
                else "Unit?"
            )
            key = "String"
            if "propertyNames" in s and "enum" in s["propertyNames"]:
                values = tuple(s["propertyNames"]["enum"])
                key = self.enum_name(values, f"{context}Key")
                if key not in ALIASES:
                    self.inline[key] = values
            return f"Map<{key}, {value}>"
        raise ValueError(f"unsupported schema {s}")

    def constraints(self, s: dict) -> str | None:
        """Kotlin cannot express the JSON-schema constraints pydantic puts in a schema, so keep them
        in the file instead of losing them: the bounds behind `ge`/`le` and the arity behind a
        fixed-length tuple, at any depth (`items`, `additionalProperties`, `prefixItems`). A keyword
        that is not listed in KNOWN_KEYWORDS raises rather than vanishing. The range checks in
        backend/contracts.py's field_validators never reach the schema at all; those are written
        down in VALIDATOR_NOTES instead.
        """
        notes: list[str] = []
        for option in s.get("anyOf", [s]):
            unknown = sorted(set(option) - KNOWN_KEYWORDS)
            if unknown:
                raise ValueError(f"unhandled JSON-schema keyword(s) {unknown} in {option}")
            for json_schema_key, word in (("minimum", "min"), ("maximum", "max")):
                if json_schema_key in option:
                    notes.append(f"{word} {option[json_schema_key]}")
            if "minItems" in option and option.get("maxItems") == option["minItems"]:
                notes.append(f"exactly {option['minItems']} numbers")
            nested = [x for x in (option.get("items"), option.get("additionalProperties"))
                      if isinstance(x, dict)]
            nested += [x for x in option.get("prefixItems", []) if isinstance(x, dict)]
            for subschema in nested:
                note = self.constraints(subschema)
                if note:
                    notes.append(note)
        return ", ".join(dict.fromkeys(notes)) or None

    def default(self, model: type[c._Contract], name: str) -> str | None:
        field = model.model_fields[name]
        if field.is_required():
            return None
        if not field.default_factory:
            if field.default is None:
                return "null"
            raise ValueError(f"{model.__name__}.{name} has a default this generator cannot write")
        factory = field.default_factory
        if issubclass(factory, dict):
            return "emptyMap()"
        if issubclass(factory, list):
            return "emptyList()"
        if isinstance(factory, type) and issubclass(factory, c._Contract):
            return f"{factory.__name__}()"
        raise ValueError(f"{model.__name__}.{name} has an unsupported default_factory {factory!r}")

    def enum_class(self, name: str, values: tuple[str, ...]) -> str:
        return (
            "/** Serialised by name: the JSON value is the lower-case entry name, verbatim. */\n"
            "@Serializable\n"
            f"enum class {name} {{\n{self.enum_body(values)}\n}}\n"
        )

    def data_class(self, model: type[c._Contract]) -> str:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        noted = {field for owner, field in VALIDATOR_NOTES if owner == model.__name__}
        unnoted = sorted(validated_fields(model) - noted)
        if unnoted:
            raise ValueError(
                f"{model.__name__}.{unnoted} has a field_validator whose rule never reaches the JSON "
                "schema; add it to VALIDATOR_NOTES so the Kotlin mirror keeps the check"
            )
        fields = []
        for name, prop in schema["properties"].items():
            note = ", ".join(
                n for n in (self.constraints(prop), VALIDATOR_NOTES.get((model.__name__, name))) if n
            )
            if note:
                fields.append(f"    /** {note} */")
            if name != camel(name):
                fields.append(f'    @SerialName("{name}")')
            default = self.default(model, name)
            declaration = f"    val {camel(name)}: {self.type(prop, model.__name__ + pascal(name))}"
            fields.append(declaration + (f" = {default}," if default else ","))
        doc = kdoc(schema.get("description", "")).strip()
        lines = ([f"/** {doc} */"] if doc else []) + [
            "@Serializable",
            f"data class {model.__name__}(",
            *fields,
            ")",
        ]
        return "\n".join(lines) + "\n"

    def file(self) -> str:
        classes = [self.data_class(m) for m in models()]  # populates self.inline
        parts = [
            HEADER,
            PACKAGE,
            "import kotlinx.serialization.SerialName\n"
            "import kotlinx.serialization.Serializable\n"
            "import kotlinx.serialization.json.Json\n",
            "/**\n"
            " * The `Json` every contract is read and written with, so the app and the wire cannot\n"
            " * disagree about the format:\n"
            " *\n"
            " *  - `ignoreUnknownKeys = false` because the pydantic models set `extra=\"forbid\"`: an\n"
            " *    unknown key fails on both sides instead of being silently dropped.\n"
            " *  - `explicitNulls = true` and `encodeDefaults = true` because `_Contract.to_json()`\n"
            " *    writes every key, nulls included, so the shape on the wire is always complete.\n"
            " */\n"
            "val ContractsJson: Json = Json {\n"
            "    ignoreUnknownKeys = false\n"
            "    explicitNulls = true\n"
            "    encodeDefaults = true\n"
            "}\n",
            "/**\n"
            " * The fixed emotion vocabulary (CLAUDE.md \"Emotion vocabulary\"), in vocabulary order.\n"
            " * Mirrors `EMOTIONS` in backend/contracts.py, and `RulesLabel.scores` always carries\n"
            " * all eight keys.\n"
            " */\n"
            "val EMOTIONS: List<Emotion> = listOf(\n"
            + "".join(f"    Emotion.{v},\n" for v in ALIASES["Emotion"])
            + ")\n",
        ]
        parts.extend(self.enum_class(name, ALIASES[name]) for name in ALIASES)
        parts.extend(self.enum_class(name, values) for name, values in self.inline.items())
        parts.extend(classes)
        return "\n".join(parts).rstrip() + "\n"


def fixture(model: type[c._Contract]) -> str:
    try:
        return model(**SAMPLES[model.__name__]).to_json() + "\n"
    except Exception as exc:  # a stale sample means contracts.py has moved on
        raise SystemExit(
            f"the {model.__name__} sample in gen_kotlin_types.py no longer validates ({exc}); "
            "update SAMPLES to match backend/contracts.py"
        ) from exc


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(KOTLIN_OUT), help="directory for Contracts.kt")
    ap.add_argument("--fixtures", default=str(FIXTURES_OUT), help="directory for the JSON fixtures")
    args = ap.parse_args()

    out, fixtures = Path(args.out), Path(args.fixtures)
    out.mkdir(parents=True, exist_ok=True)
    fixtures.mkdir(parents=True, exist_ok=True)
    (out / "Contracts.kt").write_text(Emitter().file())
    written = []
    for model in models():
        name = snake(model.__name__)
        (fixtures / f"{name}.json").write_text(fixture(model))
        written.append(name)
    print(f"wrote {out / 'Contracts.kt'} plus {len(written)} fixtures in {fixtures}: {', '.join(written)}")


if __name__ == "__main__":
    main()