// GENERATED by scripts/gen_kotlin_types.py from backend/contracts.py. Do not edit by hand.
//
// The pydantic models are the source of truth for the wire format; this file mirrors them field
// for field. Regenerate with `python scripts/gen_kotlin_types.py`: tests/web/test_kotlin_types.py
// fails while the committed file is stale, and android ContractsTest.kt fails if the types stop
// matching the Python fixtures.

package com.btb.ondevice.contracts

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * The `Json` every contract is read and written with, so the app and the wire cannot
 * disagree about the format:
 *
 *  - `ignoreUnknownKeys = false` because the pydantic models set `extra="forbid"`: an
 *    unknown key fails on both sides instead of being silently dropped.
 *  - `explicitNulls = true` and `encodeDefaults = true` because `_Contract.to_json()`
 *    writes every key, nulls included, so the shape on the wire is always complete.
 */
val ContractsJson: Json = Json {
    ignoreUnknownKeys = false
    explicitNulls = true
    encodeDefaults = true
}

/**
 * The fixed emotion vocabulary (CLAUDE.md "Emotion vocabulary"), in vocabulary order.
 * Mirrors `EMOTIONS` in backend/contracts.py, and `RulesLabel.scores` always carries
 * all eight keys.
 */
val EMOTIONS: List<Emotion> = listOf(
    Emotion.happy,
    Emotion.excited,
    Emotion.relaxed,
    Emotion.anxious,
    Emotion.fearful,
    Emotion.aggressive,
    Emotion.disinterested,
    Emotion.unknown,
)

/** Serialised by name: the JSON value is the lower-case entry name, verbatim. */
@Serializable
enum class Emotion {
    happy,
    excited,
    relaxed,
    anxious,
    fearful,
    aggressive,
    disinterested,
    unknown,
}

/** Serialised by name: the JSON value is the lower-case entry name, verbatim. */
@Serializable
enum class EarPosition {
    up,
    neutral,
    back,
    unknown,
}

/** Serialised by name: the JSON value is the lower-case entry name, verbatim. */
@Serializable
enum class AudioLabel {
    bark,
    yip,
    growl,
    whimper,
    howl,
    silence,
    other,
}

/** Serialised by name: the JSON value is the lower-case entry name, verbatim. */
@Serializable
enum class EmotionStateSource {
    rules,
    llm,
    fused,
}

/** Per-frame features. Any feature is None if its keypoints are missing or low confidence. */
@Serializable
data class Features(
    /** min -1.0, max 1.0 */
    @SerialName("tail_height")
    val tailHeight: Double? = null,
    /** min 0.0 */
    @SerialName("tail_wag_hz")
    val tailWagHz: Double? = null,
    @SerialName("ear_position")
    val earPosition: EarPosition? = null,
    /** min 0.0, max 1.0 */
    @SerialName("mouth_open")
    val mouthOpen: Double? = null,
    /** min 0.0, max 1.0 */
    @SerialName("body_lowering")
    val bodyLowering: Double? = null,
    /** min 0.0, max 1.0 */
    @SerialName("motion_energy")
    val motionEnergy: Double? = null,
    @SerialName("in_feeding_zone")
    val inFeedingZone: Boolean? = null,
)

/** Vision -> fusion, ~5-10 per second. bbox/keypoints are in full-frame pixel coords. */
@Serializable
data class FrameEvent(
    val ts: Double,
    val source: String,
    @SerialName("dog_detected")
    val dogDetected: Boolean,
    /** exactly 4 numbers */
    val bbox: List<Double>? = null,
    /** min 0.0, max 1.0 */
    @SerialName("bbox_conf")
    val bboxConf: Double? = null,
    @SerialName("body_keypoints")
    val bodyKeypoints: Map<String, List<Double>?> = emptyMap(),
    @SerialName("face_landmarks")
    val faceLandmarks: List<List<Double>>? = null,
    val features: Features = Features(),
)

/** Audio -> fusion, one per YAMNet window (~0.96 s). */
@Serializable
data class AudioEvent(
    val ts: Double,
    val label: AudioLabel,
    /** min 0.0, max 1.0 */
    val score: Double,
)

/** Rules engine output, delivered through Pipeline's on_rules_label callback. */
@Serializable
data class RulesLabel(
    val ts: Double,
    val emotion: Emotion,
    /** min 0.0, max 1.0 */
    val confidence: Double,
    val scores: Map<Emotion, Double>,
)

/** Fusion -> dashboard / notifier (owned by Web). `snapshot` is a base64 JPEG or URL, or None. */
@Serializable
data class EmotionState(
    val ts: Double,
    val emotion: Emotion,
    /** min 0.0, max 1.0 */
    val confidence: Double,
    val source: EmotionStateSource,
    val reason: String,
    val snapshot: String? = null,
)

/** One parsed LLM interpretation (Web-internal, broadcast to the dashboard as type "llm"). */
@Serializable
data class LLMResult(
    val ts: Double,
    val emotion: Emotion,
    /** min 0.0, max 1.0 */
    val confidence: Double,
    val reason: String,
    val provider: String,
    val model: String,
    @SerialName("latency_ms")
    val latencyMs: Double,
    val trigger: String,
)
