// GENERATED by scripts/gen_ts_types.py from backend/contracts.py. Do not edit.

export const EMOTIONS = ["happy", "excited", "relaxed", "anxious", "fearful", "aggressive", "disinterested", "unknown"] as const;
export type Emotion = (typeof EMOTIONS)[number];
export const AUDIO_LABELS = ["bark", "yip", "growl", "whimper", "howl", "silence", "other"] as const;
export type AudioLabel = (typeof AUDIO_LABELS)[number];
export const EAR_POSITIONS = ["up", "neutral", "back", "unknown"] as const;
export type EarPosition = (typeof EAR_POSITIONS)[number];

export interface Features {
  tail_height: number | null;
  tail_wag_hz: number | null;
  ear_position: EarPosition | null;
  mouth_open: number | null;
  body_lowering: number | null;
  motion_energy: number | null;
  in_feeding_zone: boolean | null;
}

export interface FrameEvent {
  ts: number;
  source: string;
  dog_detected: boolean;
  bbox: [number, number, number, number] | null;
  bbox_conf: number | null;
  body_keypoints: Record<string, [number, number, number] | null>;
  face_landmarks: [number, number][] | null;
  features: Features;
}

export interface AudioEvent {
  ts: number;
  label: AudioLabel;
  score: number;
}

export interface RulesLabel {
  ts: number;
  emotion: Emotion;
  confidence: number;
  scores: Partial<Record<Emotion, number>>;
}

export interface EmotionState {
  ts: number;
  emotion: Emotion;
  confidence: number;
  source: "rules" | "llm" | "fused";
  reason: string;
  snapshot: string | null;
}

export interface LLMResult {
  ts: number;
  emotion: Emotion;
  confidence: number;
  reason: string;
  provider: string;
  model: string;
  latency_ms: number;
  trigger: string;
}
