// GENERATED by scripts/gen_ts_types.py from backend/contracts.py. Do not edit.
export const CANONICAL_NAMES: readonly string[] = ["nose", "upper_jaw", "lower_jaw", "mouth_left", "mouth_right", "left_eye", "right_eye", "left_ear_base", "left_ear_tip", "right_ear_base", "right_ear_tip", "withers", "hip", "tail_base", "tail_tip", "left_front_paw", "right_front_paw", "left_back_paw", "right_back_paw"];

export const SKELETON: readonly (readonly [string, string])[] = [
  ["nose", "upper_jaw"],
  ["upper_jaw", "lower_jaw"],
  ["left_eye", "nose"],
  ["right_eye", "nose"],
  ["left_ear_base", "left_ear_tip"],
  ["right_ear_base", "right_ear_tip"],
  ["nose", "withers"],
  ["withers", "hip"],
  ["hip", "tail_base"],
  ["tail_base", "tail_tip"],
  ["withers", "left_front_paw"],
  ["withers", "right_front_paw"],
  ["hip", "left_back_paw"],
  ["hip", "right_back_paw"],
];
